services:
  backend:
    #    image: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    build: .
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    container_name: ds-backend
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ds-api.rule=Host(`api.backend.langswap.app`)"
      - "traefik.http.routers.ds-api.entrypoints=websecure"
      - "traefik.http.routers.ds-api.tls.certResolver=le"
      - "traefik.http.routers.ds-api.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.docker.network=traefik"
    networks:
      - ds-dev
      - traefik

  db:
    image: postgres
    container_name: ds-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
    networks:
      - ds-dev

  redis:
    image: redis:alpine
    container_name: ds-redis
    expose:
      - '6379'
    networks:
      - ds-dev

volumes:
  postgres_data:

networks:
  ds-dev:
    external: true
  traefik:
    external: true
