"""add arrays to processed_object

Revision ID: 50cedbf7a0ea
Revises: e084f258c8a1
Create Date: 2023-04-09 22:11:42.960127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cedbf7a0ea'
down_revision = 'e084f258c8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_object', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('processed_object', sa.Column('translated', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('processed_object', sa.Column('recognized', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_object', 'recognized')
    op.drop_column('processed_object', 'translated')
    op.drop_column('processed_object', 'progress')
    # ### end Alembic commands ###
