"""init

Revision ID: 7d360d4b9962
Revises: 
Create Date: 2023-02-23 19:10:01.519555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d360d4b9962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_link', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'in_progress', 'translation_ready', 'done', 'error', 'removed', name='processstatus'), nullable=True),
    sa.Column('prepared_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_object_id'), 'processed_object', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_object_id'), table_name='processed_object')
    op.drop_table('processed_object')
    # ### end Alembic commands ###
