"""add uuid instead of public id

Revision ID: d4d9abaa5361
Revises: 7d360d4b9962
Create Date: 2023-02-23 19:32:37.152631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d9abaa5361'
down_revision = '7d360d4b9962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_object', sa.Column('public_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_processed_object_public_id'), 'processed_object', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_object_public_id'), table_name='processed_object')
    op.drop_column('processed_object', 'public_id')
    # ### end Alembic commands ###
